[package]
name = "mpu6050-async"
version = "0.1.0"
edition = "2024"
authors = ["Breno Gabriel Barão Sanchez <brenosanchez11@gmail.com>"]
description = "An async driver for the MPU-6050 accelerometer and gyroscope using embedded-hal-async."
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal-async = "1.0"
