[package]
name = "mpu6050-async-driver"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
authors = [
    "Breno-Sanchez",
    "Jhonattan-Gabriel-D-Santana",
]
description = "A no_std async MPU-6050 driver with accelerometer, gyroscope and temperature support."
repository = "https://github.com/Breno-Sanchez/mpu6050-async-driver"
readme = "README.md"
license = "0BSD"
keywords = ["mpu6050", "imu", "i2c", "embedded", "async"]
categories = ["embedded", "hardware-support", "no-std", "asynchronous"]
exclude = [
    "/app-esp32",
    "/target",
]

[dependencies]
embedded-hal-async = "1.0"
