[package]
name = "app-esp32"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
embassy-executor = "0.10.0"
embassy-time = "0.5.0"
esp-backtrace = { version = "0.19.0", features = ["esp32", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32"] }
esp-hal = { version = "~1.1.0", features = ["esp32", "unstable"] }
esp-println = { version = "0.17.0", features = ["esp32"] }
esp-rtos = { version = "0.3.0", features = ["esp32", "embassy"] }
mpu6050-async-driver = { path = ".." }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"
